apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- common/
- app-a/
- app-b/
- app-c/
#- servicemesh/app-a-dr-vs.yml
#- servicemesh/app-b-dr-vs.yml
#- servicemesh/app-c-dr-vs.yml
#- servicemesh/gateway.yml
#- servicemesh/auth.yml

# Testing:
#   kustomize edit set image app-a:latest=image-registry.openshift-image-registry.svc:5000/user1-apps/app-a:main
#
images:
- name: app-a:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-a
  newTag: main
- name: app-b:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-b
  newTag: main
- name: app-c:latest
  newName: image-registry.openshift-image-registry.svc:5000/user1-apps/app-c
  newTag: main
