kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-example-fixme
  labels:
    app: nginx-example-fixme
    app.kubernetes.io/component: nginx-example-fixme
    app.kubernetes.io/instance: nginx-example-fixme
    app.kubernetes.io/name: nginx-example-fixme
    app.kubernetes.io/part-of: nginx-example-fixme
    app.openshift.io/runtime: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-example-fixme
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-example-fixme
        deployment: nginx-example-fixme
    spec:
      containers:
        - name: nginx-example-fixme
          image: quay.io/openshift-examples/otq-openshift/nginx-example-app:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
