apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-b
    app.kubernetes.io/component: app-b
    app.kubernetes.io/instance: app-b
    app.kubernetes.io/part-of: app-b
    app.openshift.io/runtime: redhat
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-b
        deploymentconfig: app-b
    spec:
      containers:
      - image: app-b:latest
        imagePullPolicy: Always
        name: app-b